export const card_data = [
  {
    make: "Jeep",
    model: "Wrangler",
    price: "$54,485",
    year: 2021,
    mileage: "12,000 mi",
    color: "Black",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "4 Cylinder",
    driveType: "4WD",
    condition: "Used",
    image: "./assets/c2.png" ,// Replace with actual URL,
    text:"2023 Jeep Wrangler 4X4",
    link:"456 New Place, Moose Jaw, SK S6H 2B2, Canada",
    driventain:"4X4",
    body_style:"Wagon",
    fainance:"Available",

  },
  {
    make: "Lamborghini",
    model: "Urus",
    price: "call for price",
    year: 2022,
    mileage: "5,000 mi",
    color: "Yellow",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "4 Cylinder",
    driveType: "AWD",
    condition: "New",
    image: "./assets/image 2.png",
    text:"2023 Lexus RX AWD",
    link:"456 New Place, Moose Jaw, SK S6H 2B2, Canada",
    driventain:"AWD",
    body_style:"Wagon",
    fainance:"Sold",
    red_color :"red"

  },
  {
    make: "Jeep",
    model: "Wrangler",
    price: "$47,065",
    year: 2021,
    mileage: "8,000 mi",
    color: "White",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "Electric",
    driveType: "4WD",
    condition: "Used",
    image: "./assets/image 3.png",
    text:"2021 Jeep Wrangler 4X4",
    link:"456 New Place, Moose Jaw, SK S6H 2B2, Canada",
    driventain:"4X4",
    body_style:"Wagon",
    fainance:"Available",

  },
  {
    make: "Dodge",
    model: "Durango",
    price: "call for price",
    year: 2023,
    mileage: "4,500 mi",
    color: "Black",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "6 Cylinder",
    driveType: "AWD",
    condition: "New",
    image: "./assets/image 4.png",
    text:"2021 Volkswagen Atlas AWD",
    link:"HIGHLINE|3.6 FSI 4MOTION|AWD|C...",
    driventain:"AWD",
    body_style:"SUV",
    fainance:"Available",
    red_color :"red"
  },
  {
    make: "Cadillac",
    model: "Escalade",
    price: "call for price",
    year: 2023,
    mileage: "3,000 mi",
    color: "Gray",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "8 Cylinder",
    driveType: "4WD",
    condition: "New",
    image: "./assets/image 6.png",
    text:"2021 Dodge Charger RWD",
    link:"DAYTONA|RT|5.7 HEMI|LEATHER PL...",
    body_style:"Sedan",
    fainance:"Pending",
    driventain:"RWD",
    red_color :"red"

  },
  {
    make: "BMW",
    model: "M4",
    price: "$94,605",
    year: 2022,
    mileage: "6,000 mi",
    color: "Blue",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "6 Cylinder",
    driveType: "RWD",
    condition: "New",
    image: "./assets/image 8.png",
    text:"2018 BMW M4 RWD",
    link:"M4|RWD|CABRIOLET|LEATHER INTER...",
    driventain:"RWD",
    body_style:"Convertible",
    fainance:"Upcoming"

  },
  {
    make: "Mercedes-Benz",
    model: "GLE",
    price: "call for price",
    year: 2022,
    mileage: "7,500 mi",
    color: "White",
    transmission: "Automatic",
    fuelType: "Diesel",
    engine: "6 Cylinder",
    driveType: "AWD",
    condition: "New",
    image: "./assets/image 9.png",
    text:"2021 Volkswagen Atlas AWD",
    link:"HIGHLINE|3.6 FSI 4MOTION|AWD|C...",
    driventain:"AWD",
    body_style:"SUV",
    fainance:"Upcoming",
    red_color :"red"
    

  },
  {
    make: "Dodge",
    model: "Charger",
    price: "call for price",
    year: 2022,
    mileage: "8,200 mi",
    color: "White",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "8 Cylinder",
    driveType: "RWD",
    condition: "Used",
    image: "./assets/image 2.png",
    text:"2021 Dodge Charger RWD",
    link:"DAYTONA|RT|5.7 HEMI|LEATHER PL...",
    driventain:"RWD",
    body_style:"Sedan",
    fainance:"Sold",
    red_color :"red"


  },
  {
    make: "BMW",
    model: "X6",
    price: "$64,698",
    year: 2023,
    mileage: "3,300 mi",
    color: "Silver",
    transmission: "Automatic",
    fuelType: "Gasoline",
    engine: "6 Cylinder",
    driveType: "AWD",
    condition: "New",
    image: "./assets/c2.png",
    text:"2018 BMW M4 RWD",
    link:"M4|RWD|CABRIOLET|LEATHER INTER...",
    driventain:"RWD",
    body_style:"Convrtible",
    fainance:"Pending",

  }
];
